#pragma config(Motor,  motorA,          RND,           tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          UP,            tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define RNDVAL 210

ubyte Rec[2];

int GUp;
int GRnd;

int MUp;
int MRnd;

int distUp;
int distRnd;

void checkBTLinkConnected();

task main(){
  nMotorEncoder[UP] = 0;
  nMotorEncoder[RND] = 0;
  MUp = 0;
  MRnd = 0;
  distUp = 0;
  distRnd = 0;

  checkBTLinkConnected();

  while(true){
    wait1Msec(1);
    cCmdMessageRead(Rec, 2, mailbox1);

    nxtDisplayTextLine(1,"UP=%d,RND=%d",Rec[0], Rec[1]);

    if(Rec[1] != 0){
      GUp = Rec[0]-1;
      GRnd = Rec[1]-6;
    }
    else{
      GUp = 0;
      GRnd = 0;
    }

    MUp = GUp * 40;
    MRnd = -(GRnd * 40);

    nxtDisplayTextLine(2,"MUP=%d,MRND=%d",MUp, MRnd);

    nxtDisplayTextLine(3,"UP = %d",nMotorEncoder[UP]);
    nxtDisplayTextLine(4,"RND = %d",nMotorEncoder[RND]);

    distUp = MUp-nMotorEncoder[UP];
    if(MUp != nMotorEncoder[UP]){
      motor[UP] = distUp;
    }
    else{
      motor[UP] = 0;
    }

    distRnd = MRnd-nMotorEncoder[RND];
    if(MRnd != nMotorEncoder[UP]){
      motor[RND] = distRnd;
    }
    else{
      motor[RND] = 0;
    }

  }
}

void checkBTLinkConnected()
{
	if (nBTCurrentStreamIndex >= 0)
	  return;

	PlaySound(soundLowBuzz);
	PlaySound(soundLowBuzz);
	eraseDisplay();
	nxtDisplayCenteredTextLine(3, "BT not");
	nxtDisplayCenteredTextLine(4, "Connected");
	wait1Msec(3000);
	StopAllTasks();
}
