#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    ,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_3,    ,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_4,    ,                     tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LftRec;
int RgtRec;

int RgtGUp;
int RgtGRnd;
int LftGUp;
int LftGRnd;

int RgtMUp;
int RgtMRnd;
int LftMUp;
int LftMRnd;

void checkBTLinkConnected();

task main(){
  RgtMUp = 0;
  RgtMRnd = 0;
  LftMUp = 0;
  LftMRnd = 0;

  checkBTLinkConnected();
  while(true){
    wait1Msec(1);
    while (bQueuedMsgAvailable()){
      ClearMessage();
      LftRec = messageParm[0];
      RgtRec = messageParm[1];
    }
    /*if(message == 0){
      wait1Msec(5);
      nxtDisplayTextLine(2,"no message");
      continue;
    }*/

    nxtDisplayTextLine(1,"message[0] = %d",LftRec);
    nxtDisplayTextLine(2,"message[1] = %d",RgtRec);

    LftGUp = LftRec/100;
    LftGRnd = LftRec%100;

    RgtGUp = RgtRec/100;
    RgtGRnd = RgtRec%100;

    RgtMUp = RgtGUp * 16;
    RgtMRnd = (RgtGRnd * 16);
    LftMUp = LftGUp * 16;
    LftMRnd = (LftGRnd * 16);

    nxtDisplayTextLine(3,"RGU = %d",RgtGUp);
    nxtDisplayTextLine(4,"RGR = %d",RgtGRnd);
    nxtDisplayTextLine(5,"LGU = %d",LftGUp);
    nxtDisplayTextLine(6,"LGR = %d",LftGRnd);

    servo[srvo_S1_C2_1] = RgtMUp;
    servo[srvo_S1_C2_2] = RgtMRnd;
    servo[srvo_S1_C2_3] = LftMUp;
    servo[srvo_S1_C2_4] = LftMRnd;

  }
}

void checkBTLinkConnected()
{
	if (nBTCurrentStreamIndex >= 0)
	  return;

	PlaySound(soundLowBuzz);
	PlaySound(soundLowBuzz);
	eraseDisplay();
	nxtDisplayCenteredTextLine(3, "BT not");
	nxtDisplayCenteredTextLine(4, "Connected");
	wait1Msec(3000);
	StopAllTasks();
}
