#pragma config(Sensor, S1,     GYROUP,              sensorLowSpeed)
#pragma config(Sensor, S2,     GYROROUND,              sensorLowSpeed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "drivers/HTGYRO-driver.h"

long headingUp;
long accumulatorUp;
long headingRound;
long accumulatorRound;
int time;
long sendUp;
long sendRound;
long sendFin;
int nTime;

void checkBTLinkConnected();

task main (){
  checkBTLinkConnected();


  accumulatorUp=0;
  headingUp = 0;
  accumulatorRound=0;
  headingRound = 0;
  time = 0;
  nTime = 0;
  sendFin = 0;


  HTGYROstartCal(GYROUP);
  HTGYROstartCal(GYROROUND);

  while(true){
    wait1Msec(1);

    accumulatorUp+=HTGYROreadRot(GYROUP);
    accumulatorRound+=HTGYROreadRot(GYROROUND);
    if(time == 10){
      eraseDisplay();

      headingUp += accumulatorUp*1;
      headingRound += accumulatorRound*1;

      sendUp = headingUp*0.0001;
      sendRound = (headingRound*0.0001)+8;
      sendFin = (sendUp*100)+ sendRound;

      if(nTime == 10){
        sendMessageWithParm(sendFin);
        nTime = 0;
      }

      nxtDisplayTextLine(1,"hU = %d",sendUp);
      nxtDisplayTextLine(2,"hR = %d",sendRound);
      nxtDisplayTextLine(3,"Press [] to reset");
      nxtDisplayTextLine(4,"hS = %d",sendFin);

      accumulatorUp = 0;
      accumulatorRound = 0;
      time = 0;
      ++nTime;

    }
    if(nNxtButtonPressed == kEnterButton) {

      headingUp = 0;
      HTGYROstartCal(GYROUP);

      headingRound = 0;
      HTGYROstartCal(GYROROUND);
    }
    ++time;
  }
}

void checkBTLinkConnected()
{
	if (nBTCurrentStreamIndex >= 0)
	  return;

	PlaySound(soundLowBuzz);
	PlaySound(soundLowBuzz);
	eraseDisplay();
	nxtDisplayCenteredTextLine(3, "BT not");
	nxtDisplayCenteredTextLine(4, "Connected");
	wait1Msec(3000);
	StopAllTasks();
}
