#pragma config(Sensor, S3,     lightSensor,         sensorLightActive)
#pragma config(Sensor, S4,     lightSensor2,         sensorLightActive)
#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                           - Line Tracker -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program allows your taskbot to follow a line in reverse.                                         *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Light Sensor is attached to the back of the robot.                                          *|
|*    2)  Be sure to take readings of your Light Sensor over the light and dark areas.  Once you have     *|
|*        the values, add them and divide by 2 to find your threshold.  Then, use your threshold as a     *|
|*        comparison in your program.                                                                     *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 1                  lightSensor         Light Sensor        Back mounted                        *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
   wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

   while(true)                           // Infinite loop
   {
     while(SensorValue[lightSensor] > 35 && SensorValue[lightSensor2] > 35){

         motor[motorD] = 20;   // Motor D is run at a power level of 25.
   motor[motorE] = 20;   // Motor E is run at a power level of 25.
     }
     while(SensorValue[lightSensor] < 35 && SensorValue[lightSensor2] > 35){
       while(SensorValue[lightSensor2] > 35){
         motor[motorD] = 5;   // Motor D is run at a power level of 25.
   motor[motorE] = 40;   // Motor E is run at a power level of 25.
 }
     }
     while(SensorValue[lightSensor] > 35 && SensorValue[lightSensor2] < 35){
       while(SensorValue[lightSensor] > 35){
         motor[motorD] = 40;   // Motor D is run at a power level of 25.
   motor[motorE] = 5;   // Motor E is run at a power level of 25.
 }
     }
      /*if(SensorValue[lightSensor] < 35)  // If the Light Sensor reads a value less than 45:
      {
     motor[motorD] = 40;   // Motor D is run at a power level of 25.
   motor[motorE] = 5;   // Motor E is run at a power level of 25.
      }
      else                               // If the Light Sensor reads a value greater than or equal to 45:
      {
        if

       motor[motorD] = 5;   // Motor D is run at a power level of 25.
   motor[motorE] = 40;   // Motor E is run at a power level of 25.
      }*/
   }
}
