#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    ,                     tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                chuckrec-for servo
////////////////////////////////////////////////////////////////////////////////////////////////////////







ubyte nMessage[4];




//
// Function Prorotype Declarations
//
int ubyteToInt(ubyte _byte) {
  int _ret = 0;
_ret = (_byte & 0x80) ? (_byte & 0x7F) + 0x80 : _byte;
  return _ret;
}

void checkBTLinkConnected();
void readMessages();


////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                        Main Task
//
////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  while(true){
	//
	// Test Ability to Turn Bluetooth On or Off
	//
	checkBTLinkConnected();
	eraseDisplay();
	bNxtLCDStatusDisplay = true; // Enable top status line display


	readMessages();
	wait1Msec(100);
	return;
}
}




////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                        Receive Messages
////////////////////////////////////////////////////////////////////////////////////////////////////////

void readMessages()
{


	while (true)
	{
	  cCmdMessageRead(nMessage, 4, mailbox1);

	  int Axis1 = nMessage[0]-100;
	  int Axis2 = nMessage[1]-100;
	  int Axis3 = nMessage[3]-100;
	  nxtDisplayTextLine(2,"1 = %d", Axis2);

	   if(Axis1 < 0){
	     Axis1 = Axis1+55;
	     Axis1 = Axis1*1.275;
	   }

	   else{
	     Axis1 =  Axis1 = Axis1*1.275;
	   }

	   if(Axis2 < 0){
	     Axis2 = Axis2+100;
	     Axis2 = Axis2*1.275;
	   }

	   else{
	     Axis2 =  Axis2 = Axis2*1.275;
	   }

	   if(Axis3 < 0){
	     Axis3 = Axis3+100;
	     Axis3 = Axis3*1.275;
	   }

	   else{
	     Axis3 =  Axis3 = Axis3*1.275;
	   }


   // nxtDisplayTextLine(2,"1 = %d", Axis1);

    servo[servo1] = Axis1;
    servo[servo2] = Axis2;
    //servo[srvo_S1_C2_3] = LftMUp;
    //servo[srvo_S1_C2_4] = LftMRnd;

    }


		}



////////////////////////////////////////////////////////////////////////////////////////////////////////

void checkBTLinkConnected()
{
	if (nBTCurrentStreamIndex >= 0)
	  return;

	PlaySound(soundLowBuzz);
	PlaySound(soundLowBuzz);
	eraseDisplay();
	nxtDisplayCenteredTextLine(3, "BT not");
	nxtDisplayCenteredTextLine(4, "Connected");
	wait1Msec(3000);
	StopAllTasks();
}
