#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    ,                     tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Author : Soham Sankaran, 4rd October 2010
/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                              - SoYaRu 0.03 -                                              *|
|*                                          ROBOTC on NXT + TETRIX                                        *|
|*                                                                                                        *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*       Note: Unless you write to them, all the servos on the board will reset to 127.5 or 0             *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 1                  none                TETRIX Controller   TETRIX                              *|
|*    Port 1 - Chan. 1       srvo_S1_C2_1         std. Servo          Arm Up-Down Servo                   *|
|*    Port 1 - Chan. 2       srvo_S1_C2_2         std. Servo          Arm Right-Left Servo                *|
|*    Port A                    motorA            NXT Motor           Elbow Up-Down Motor                 *|
|*    Port B                    motorB            NXT Motor           Elbow Right-Left Motor              *|
\*---------------------------------------------------------------------------------------------------4246-*/

#include "DaRWIn-Lib-0.1.c"

task main()
{
  int delta = 2;                        // Create int 'delta' to the be Servo Change Rate(Speed).

  //begin initial setup code(do not change)
  servoChangeRate[srvo_S1_C2_1] = delta;
  servoChangeRate[srvo_S1_C2_2] = delta;

  nMotorEncoder[motorA]=0;              //reset motorA's encoder
  nMotorEncoder[motorB]=0;              //reset motorB's encoder

  ResetToNamaste();

 // ServoFreeze(1,200);
  //end initial setup code
 // while(true)
 // {
    //servo[srvo_S1_C2_1] = 255;
    //ServoFreeze(1, 123);

  //}
}
