#pragma config(Sensor, S1,     HTGYRO,              sensorLowSpeed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/HTGYRO-driver.h"

int heading;
int accumulator;
int time;
task main (){
  accumulator=0;
  heading = 0;
  time = 0;
  HTGYROstartCal(HTGYRO);
  while(true){
    wait1Msec(1);

    accumulator+=HTGYROreadRot(HTGYRO);
    if(time == 10){
      eraseDisplay();
      heading += accumulator*0.01;
      nxtDisplayTextLine(0,"acc = %d",accumulator);
      nxtDisplayTextLine(1,"heading = %d",heading);
      nxtDisplayTextLine(2,"offset = %d",HTGYROreadCal(HTGYRO));
      nxtDisplayBigTextLine(3,"Press enter to reset");
      accumulator = 0;
      time = 0;
      wait1Msec(100);
    }
    while(nNxtButtonPressed == kEnterButton) {
      heading = 0;
      HTGYROstartCal(HTGYRO);
    }
    ++time;
  }
}
